name: 🪄 Deploy to HF Space
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: 🤗 Sync to Space
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: 'Phonginhere/cos40006'
          huggingface_repo_id: 'cos40006/persona_conflict_detection'
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: 'space'
          private: false
          space_sdk: 'docker'
          subdirectory: ''