name: 🪄 Deploy to HF Space
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true      # ensure Git-LFS files are fetched
      - name: 🤗 Sync to Space
        uses: HuggingFace/push-to-hub-action@main
        with:
          repo_id: cos40006/persona_conflict_detection
          repo_type: space
          token: ${{ secrets.HF_TOKEN }}   # store your PAT as a GitHub Secret